version: "3"

services:
  app:
    depends_on:
      - db
    build: .
    ports:
      - 5555:5555
    networks:
      - mynetwork

    environment:
      DB_HOST: db
      SERVER_HOST: app
    env_file:
      - ./.env
    container_name: bun_server

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: codingdestro
      POSTGRES_DB: gadgetBucket
    networks:
      - mynetwork
    container_name: database
    volumes:
      - /postdata/:/var/lib/postgresql/data

networks:
  mynetwork:

volumes:
  postData:
